# Generated by Django 6.0.7 on 2026-08-29 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0011_remove_constructionstatus_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_for_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True)),
                ('category_text', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('city_text', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('postal_code_text', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True)),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('cid', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('business_status', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow Up', 'Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Send Ditails', 'Send Ditails'), ('Deal Done', 'Deal Done')], default='New', max_length=25)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'SUBLOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realty_area', to='utility.location')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_realty', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'DISTRICT_CITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realty_city', to='utility.location')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'LOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realty_locality', to='utility.location')),
                ('postal_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realty_postal_code', to='utility.postalcode')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Realty',
                'verbose_name_plural': '0. Realty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Meeting', max_length=25)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_realty_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('realty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='gmbdata.realty')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': '1. Meetings',
                'ordering': ('-meeting_date',),
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Followup', max_length=25)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_realty_followups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('realty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='gmbdata.realty')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': '2. Follow Ups',
                'ordering': ('-followup_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('realty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gmbdata.realty')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_realty_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('realty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gmbdata.realty')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='voice_recordings/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('realty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='gmbdata.realty')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realty_voice_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Recording',
                'verbose_name_plural': 'Voice Recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
