# Generated by Django 6.0.7 on 2026-08-29 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbdata', '0001_initial'),
        ('utility', '0011_remove_constructionstatus_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow Up', 'Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Send Ditails', 'Send Ditails'), ('Deal Done', 'Deal Done')], db_index=True, default='New', max_length=25),
        ),
        migrations.CreateModel(
            name='Refrense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Meeting_FollowUp', 'Meeting-Follow Up')], db_index=True, default='New', max_length=25)),
                ('refrense_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_no', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('other_no', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('google_map', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('business_status_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='refrense/logo/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'SUBLOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refrense_area', to='utility.location')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_refrenses', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'DISTRICT_CITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refrense_city', to='utility.location')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'LOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refrense_locality', to='utility.location')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refrense',
                'verbose_name_plural': '4. Refrenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
