# Generated by Django 6.0.7 on 2026-08-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmbdata', '0002_alter_realty_status_refrense'),
        ('utility', '0011_remove_constructionstatus_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='realty',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refrense',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_for_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True)),
                ('category_text', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('other_phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('city_text', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('postal_code_text', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True)),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('cid', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('business_status', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow Up', 'Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Send Ditails', 'Send Ditails'), ('Deal Done', 'Deal Done')], db_index=True, default='New', max_length=25)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'SUBLOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interior_area', to='utility.location')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interiors', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'DISTRICT_CITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interior_city', to='utility.location')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'LOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interior_locality', to='utility.location')),
                ('postal_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interior_postal_code', to='utility.postalcode')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interior',
                'verbose_name_plural': '1. Interiors',
                'ordering': ['-created_at'],
            },
        ),
    ]
