# Generated by Django 6.0.7 on 2026-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
